language: java

sudo: true

before-install:
  - echo "Installation des d√©pendences qui ne disposent pas de pom.xml."
  - mvn -v
  - mvn install:install-file -Dfile=src/main/resources/WyLog_v2.jar -DgroupId=net.wytrem.logging -DartifactId=wylog -Dversion=2.0 -Dpackaging=jar
